algorithm:
  policy: MultiInputPolicy
  policy_kwargs:
    features_extractor_class: StateExtractor
    features_extractor_kwargs:
      net_arch:
        state:
          layer: [192]

    net_arch:
      pi: [192, 96]
      qf: [192, 96]

    activation_fn: relu
    optimizer_kwargs:
      weight_decay: 0.00001
    share_features_extractor: False
  learning_rate: 0.01
  horizon: 96
  tau: 0.005
  gamma: 0.99
  device: cuda
  gradient_steps: 10
  train_freq: 100
  batch_size: 25600
  actor_batch_size: 100
  actor_gradient_steps: 1
  ent_coef: 0.0000

learn:
  total_timesteps: 1000000
  log_interval: 100