algorithm:
  policy: SimplePolicy
  policy_kwargs:
    features_extractor_class: FlexibleExtractor
    features_extractor_kwargs:
      net_arch:
        color:
          layer: [256, 256]
    critic:
      dist: symlog_disc
      n_critics: 1
      net_arch:
        layer: [512, 512]
    actor:
      dist: tanh_normal
#      squash_output: False
      net_arch:
        layer: [512, 512]
#    ln: True
    activation_fn: relu
    optimizer_class: adam
    optimizer_kwargs:
      weight_decay: 0.00001
  learning_rate: 0.001
  horizon: 36
  tau: 0.005
  gamma: 0.99
  device: cuda
  gradient_steps: 10
  train_freq: 96
  batch_size: 25600
  actor_gradient_steps: 1

learn:
  total_timesteps: 20000000
  log_interval: 1

test:
  is_fig: True
  is_fig_save: True
  is_video: True
  is_video_save: True
  render_kwargs: { }